# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - vertical_whitespace
  - trailing_whitespace
  - trailing_newline
  - identifier_name
  - line_length

force_cast: warning # implicitly

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

file_length:
  warning: 500
  error: 1200
